"""V2 development audit only. Never changes the frozen v1 scorer or invents gold."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import Counter
from pathlib import Path

ROUTES = ("fixed_retrieval", "fixed_rerank", "adaptive")


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def percentile(values, q):
    values = sorted(values)
    x = (len(values) - 1) * q
    return values[math.floor(x)] + (values[math.ceil(x)] - values[math.floor(x)]) * (x % 1)


def outcome(row):
    if any(e["stage"] == "failure" for e in row["events"]):
        if row["answer"] is not None:
            raise ValueError("terminal failure with answer")
        return "terminal_failure"
    if row["answer"] is not None:
        return "mechanically_accepted_semantics_unmeasured"
    if row["reason"] == "validation_repair_exhausted":
        return "validation_repair_exhausted"
    decisions = [e["decision"] for e in row["events"] if e["stage"] == "decision"]
    if decisions and decisions[-1]["action"] == "abstain" and row["reason"] == decisions[-1]["reason"]:
        return "model_requested_abstention"
    return "controller_rejection"


def audit(run, protocol):
    if (run["phase"] != "pilot" or protocol["official_gold_available"]
            or run["budget"]["controller_protocol"] != "feedback-v2"
            or run["study_kind"] != protocol["study_kind"] or run["corpus_sha256"] != protocol["corpus_sha256"]
            or run["budget"] != protocol["budget"] or run["dense_enabled"]):
        raise ValueError("development protocol mismatch")
    tasks = {t["id"]: t["claim_text"] for t in protocol["pilot"]}
    if len(tasks) != len(protocol["pilot"]) or protocol["strategies"] != list(ROUTES):
        raise ValueError("task or route mismatch")
    expected = Counter((t, r) for t in tasks for r in ROUTES)
    if Counter((r["task_id"], r["strategy"]) for r in run["runs"]) != expected:
        raise ValueError("incomplete/duplicate matrix")
    routes = {}
    for route in ROUTES:
        rows = [r for r in run["runs"] if r["strategy"] == route]
        attempts = []
        budget_errors = Counter()
        model_actions = Counter()
        feedback_reasons = Counter()
        model_tools = Counter()
        terminal_after_tool = answer_after_tool = 0
        changed_context_tools = 0
        for row in rows:
            if row["claim_text"] != tasks[row["task_id"]] or row["provider_kind"] != "local_model":
                raise ValueError("task/provider identity mismatch")
            attempts.extend(row["generation_attempts"])
            if len(row["generation_attempts"]) != row["generation_calls"]:
                raise ValueError("attempt count mismatch")
            for key in ("input_tokens", "output_tokens"):
                if sum(a["usage"].get(key, 0) for a in row["generation_attempts"]) != row["usage"][key]:
                    raise ValueError("attempt token ledger differs from row total")
            checks = {"generation": row["generation_calls"] > run["budget"]["max_model_calls"],
                      "tools": row["tool_calls"] > run["budget"]["max_tool_calls"],
                      "repairs": row["validation_repairs"] > run["budget"]["max_validation_repairs"],
                      "deadline_late_answer": row["elapsed_ms"] > run["budget"]["timeout_seconds"] * 1000 and row["answer"] is not None}
            budget_errors.update(k for k, value in checks.items() if value)
            for attempt in row["generation_attempts"]:
                for kind in ("input", "output"):
                    if attempt["usage"].get(kind + "_tokens", 0) > run["budget"][f"max_{kind}_tokens_per_call"]:
                        budget_errors[kind + "_tokens"] += 1
            selected_tool_indices = []
            for i, event in enumerate(row["events"]):
                if event["stage"] == "decision":
                    model_actions[event["decision"]["action"]] += 1
                if event["stage"] == "validation_feedback":
                    # This field is generated by the controller, never model reason text.
                    feedback_reasons[event["category"]] += 1
                feedback = event.get("feedback", {})
                if feedback.get("model_selected"):
                    model_tools[event["stage"]] += 1
                    selected_tool_indices.append(i)
                    changed_context_tools += int(feedback["context_order_changed"])
            followed = any(e["stage"] == "decision" and e["decision"]["action"] in {"answer", "abstain"}
                           for i in selected_tool_indices for e in row["events"][i + 1:])
            terminal_after_tool += int(followed)
            answer_after_tool += int(followed and row["answer"] is not None)
        routes[route] = {
            "tasks": len(rows), "outcomes": dict(Counter(outcome(r) for r in rows)),
            "parsed_model_actions": dict(model_actions), "completed_model_selected_tools": dict(model_tools),
            "rows_with_tool_then_terminal_model_decision": terminal_after_tool,
            "rows_with_tool_then_mechanically_accepted_answer": answer_after_tool,
            "model_selected_tools_changing_context_order": changed_context_tools,
            "controller_validation_feedback": dict(feedback_reasons),
            "generation_attempt_status": dict(Counter(a["status"] for a in attempts)),
            "generation_diagnostic_categories": dict(Counter(a.get("diagnostics", {}).get("category", "unrecorded") for a in attempts)),
            "generation_attempts": len(attempts), "unknown_usage_attempts": sum(not a["usage_known"] for a in attempts),
            "input_tokens": sum(r["usage"]["input_tokens"] for r in rows),
            "output_tokens": sum(r["usage"]["output_tokens"] for r in rows),
            "invalid_response_tokens": {k: sum(a["usage"].get(k, 0) for a in attempts if a["status"] == "response_invalid")
                                        for k in ("input_tokens", "output_tokens")},
            "tool_calls": sum(r["tool_calls"] for r in rows),
            "rerank_pairs": sum(r["rerank_candidate_pairs"] for r in rows),
            "latency_ms_p50": percentile([r["elapsed_ms"] for r in rows], .5),
            "latency_ms_p95": percentile([r["elapsed_ms"] for r in rows], .95),
            "request_elapsed_ms_sum": sum(r["elapsed_ms"] for r in rows),
            "rerank_elapsed_ms_sum": sum(e["elapsed_ms"] for r in rows for e in r["events"] if e["stage"] == "rerank"),
            "budget_violation_counts": dict(budget_errors),
        }
    return {"schema_version": "feedback-development-audit-v2", "source_git": run["code_sha"],
            "protocol_sha256": run["protocol_sha256"], "corpus_sha256": run["corpus_sha256"],
            "model_sha256": run["model_sha256"], "reranker_sha256": run["reranker_sha256"],
            "prompt_identity": run["prompt_identity"], "budget": run["budget"],
            "complete_slots": len(run["runs"]), "routes": routes,
            "retrieval_quality": None, "semantic_support_quality": None,
            "boundary": "Consumed authored development tasks; not independent gold. Mechanical acceptance, tool execution and semantic quality are distinct. All failed/repair attempts count; fixed routes share limits not equal actual work. No raw text or task/evidence IDs exported."}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, required=True)
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument("--expected-protocol-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    raw, protocol_raw = args.run.read_bytes(), args.protocol.read_bytes()
    if sha(protocol_raw) != args.expected_protocol_sha256:
        raise ValueError("protocol SHA mismatch")
    result = audit(json.loads(raw), json.loads(protocol_raw))
    if result["protocol_sha256"] != sha(protocol_raw):
        raise ValueError("run bound to different protocol")
    result["private_run_receipt"] = {"sha256": sha(raw), "bytes": len(raw)}
    result["audit_script_sha256"] = sha(Path(__file__).read_bytes())
    with args.output.open("x", encoding="utf-8") as stream:
        json.dump(result, stream, indent=2, sort_keys=True)
        stream.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
